Update razy-install

diff --git a/razy-install b/razy-install
--- a/razy-install
+++ b/razy-install
@@ -1,28 +1,1 @@
-#!/data/data/com.termux/files/usr/bin/bash -e
-clear
-echo -e "\e[34m\e[1m
-                                                                         
-                                                                         
-RRRRRRRRRRRRRRRRR                                   YYYYYYY       YYYYYYY
-R::::::::::::::::R                                  Y:::::Y       Y:::::Y
-R::::::RRRRRR:::::R                                 Y:::::Y       Y:::::Y
-RR:::::R     R:::::R                                Y::::::Y     Y::::::Y
-  R::::R     R:::::R aaaaaaaaaaaaa  zzzzzzzzzzzzzzzzYYY:::::Y   Y:::::YYY
-  R::::R     R:::::R a::::::::::::a z:::::::::::::::z  Y:::::Y Y:::::Y   
-  R::::RRRRRR:::::R  aaaaaaaaa:::::az::::::::::::::z    Y:::::Y:::::Y    
-  R:::::::::::::RR            a::::azzzzzzzz::::::z      Y:::::::::Y     
-  R::::RRRRRR:::::R    aaaaaaa:::::a      z::::::z        Y:::::::Y      
-  R::::R     R:::::R aa::::::::::::a     z::::::z          Y:::::Y       
-  R::::R     R:::::Ra::::aaaa::::::a    z::::::z           Y:::::Y       
-  R::::R     R:::::a::::a    a:::::a   z::::::z            Y:::::Y       
-RR:::::R     R:::::a::::a    a:::::a  z::::::zzzzzzzz      Y:::::Y       
-R::::::R     R:::::a:::::aaaa::::::a z::::::::::::::z   YYYY:::::YYYY    
-R::::::R     R:::::Ra::::::::::aa:::z:::::::::::::::z   Y:::::::::::Y    
-RRRRRRRR     RRRRRRR aaaaaaaaaa  aaazzzzzzzzzzzzzzzzz   YYYYYYYYYYYYY    
-                                                                         
-                                                                         
-                                                                         
-"
-echo -e "\e[34m\e[1m   [1] Enter For Full"
-echo -e "\e[34m\e[1m   [2] Enter For Lite"
-echo -e "\e[34m\e[1m   [3] Enter For Nano"
+#!/bin/bash # Display menu options echo "Please select an option:" echo "1. List files and directories" echo "2. Option 2 (Placeholder)" echo "3. Option 3 (Placeholder)" read -p "Enter your choice (1/2/3): " choice # Process user choice case $choice in 1) echo "Listing files and directories:" ls ;; 2) echo "Option 2 selected. Functionality to be added." ;; 3) echo "Option 3 selected. Functionality to be added." ;; *) echo "Invalid selection. Exiting." exit 1 ;; esac
